name: MSBuild debug server.yml

on: [push]

env:
  SOLUTION_FILE_PATH: ./src_vs_2019/server/
  BUILD_CONFIGURATION: Debug
  RS2D_HOME: D:\a\sfml-rs2d\sfml-rs2d
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
    
    - name: Unzip-Dependencies
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cd D:/a/sfml-rs2d/sfml-rs2d/include && tar -xf SFML-2.5.1.zip && tar -xf boost_1_77_0.zip && tar -xf websocketpp.zip

    - name: Build-App
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /t:app:Rebuild /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build-Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /t:tests:Rebuild /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: D:\a\sfml-rs2d\sfml-rs2d\src_vs_2019\server\Debug\tests.exe --gtest_filter=-SQLDB*
