name: MSBuild debug server.yml

on: [push]

env:
  SOLUTION_FILE_PATH: ./src/server/

  BUILD_CONFIGURATION: Debug
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
    
    - name: Unzip-Dependencies
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: tar -xf %RS2D_HOME%/include/SFML-2.5.1.zip && move /Y SFML-2.5.1 %RS2D_HOME%/include && \
           tar -xf %RS2D_HOME%/include/boost_1_77_0.zip && move /Y boost_1_77_0 %RS2D_HOME%/include && \
           tar -xf %RS2D_HOME%/include/websocketpp.zip && move /Y websocketpp %RS2D_HOME%/include

    - name: Build-App
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /t:app:Rebuild /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build-Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /t:tests:Rebuild /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: D:\a\sfml-rs2d\sfml-rs2d\src\server\Debug\tests.exe --gtest_filter=-SQLDB*
